apiVersion: v1 #it is version of your kubernetes api
kind: Pod
metadata:
  name: nginx
  #namespace: myapp 
  labels:
    app: dev1
    type: nginx1
spec:
  containers:
    - name: nginx
      image: nginx
   
